In [2]:
import pandas as pd
import numpy as np

In [37]:
# Creating an array, checking its dimension and shape
array = np.array([0, 2, 4, 6, 8, 10], dtype=int)
array

array([ 0,  2,  4,  6,  8, 10])

In [13]:
array.ndim

1

In [34]:
array.size

6

In [58]:
# 2
array_2d = np.random.randint(0, 50, size=(4,3))
array_2d

array([[34, 17, 45],
       [21, 34, 19],
       [49, 39, 45],
       [ 1, 36, 26]])

In [59]:
print(array_2d.ndim)
print(array_2d.size)
print(f'array_2d has {array_2d.shape[-2]} rows and {array_2d.shape[-1]} columns.')
print(array_2d[1, :])
print(array_2d[2, 2])

2
12
array_2d has 4 rows and 3 columns.
[21 34 19]
45


In [60]:
array_3d = np.random.randint(0, 50, size=(3,5,6))
array_3d

array([[[26, 22, 24, 41,  3, 19],
        [ 8, 44, 42, 43,  3, 22],
        [26, 35, 40, 12,  3,  3],
        [39, 29, 32,  8, 33, 21],
        [26, 48,  8, 41,  6, 40]],

       [[36, 39,  5,  1, 41, 19],
        [ 6, 46, 37,  2,  0, 45],
        [29, 39, 31, 37, 27, 39],
        [39, 32, 13, 34, 47, 41],
        [49, 31, 10, 24,  7, 47]],

       [[18, 24, 16, 18, 45,  4],
        [49, 20, 24, 25, 47, 18],
        [ 6, 29, 34,  7, 41,  7],
        [44,  1, 25,  3, 45, 14],
        [ 6, 48, 27, 23, 13, 32]]])

In [61]:
print(array_3d.ndim)
print(array_3d.size)
print(f'array_3d has {array_3d.shape[-2]} rows and {array_3d.shape[-1]} columns.')
print(array_3d[1, 2, 3])
print(array_3d[0, 3:, 2:5])

3
90
array_3d has 5 rows and 6 columns.
37
[[32  8 33]
 [ 8 41  6]]


In [63]:
# 3
array_1d = np.random.randint(0, 50, size=6)
array_2d = np.random.randint(0, 50, size=(2, 7))
array_3d = np.random.randint(0, 50, size=(3, 4, 5))

In [64]:
print(array_1d)
print(array_1d[3:])
print(array_1d[4])

[32 40 32 29 38 23]
[29 38 23]
38


In [65]:
print(array_2d)
print(array_2d[:, :])
print(array_2d[1, 3:])
print(array_2d[0, 2])

[[43 40 34 19 40 22 28]
 [43  1  8 21 15 28 40]]
[[43 40 34 19 40 22 28]
 [43  1  8 21 15 28 40]]
[21 15 28 40]
34


In [67]:
print(array_3d)
print(array_3d[1:, 2:, 3:])
print(array_3d[2, 2, 2])
print(array_3d[0, 1:, 4])

[[[49 38 16 38 10]
  [45 25 38 15 14]
  [31 12 33 36 26]
  [39 29 36 16  6]]

 [[ 0 23  3 11 13]
  [22 23 49  7 20]
  [34  6 46 29  0]
  [ 1  1 41 25  4]]

 [[ 0 11 11 16  5]
  [41  6  8 31 15]
  [32 48 35 29 29]
  [38 21 49 30 27]]]
[[[29  0]
  [25  4]]

 [[29 29]
  [30 27]]]
35
[14 26  6]


In [82]:
# 4
zeros = np.zeros((3,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
ones = np.ones((3,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [91]:
mixed1 = np.concatenate((zeros, ones), axis=0)
mixed1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [92]:
mixed2 = np.concatenate((zeros, ones), axis=1)
mixed2

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [93]:
mixed1.reshape((2, 9))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [94]:
mixed2.reshape((9, 2))

array([[0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1]])